# Generated by Django 4.2.6 on 2023-10-31 13:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('avatar', models.CharField(default='', max_length=60)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100)),
                ('work', models.CharField(blank=True, max_length=150)),
                ('educations', models.TextField(blank=True)),
                ('relationship_status', models.CharField(blank=True, choices=[('single', 'Single'), ('relationship', 'In a Relationship'), ('married', 'Married'), ('complicated', "It's Complicated"), ('open', 'Open Relationship'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='posts/videos/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_social.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Запрос отправлен'), ('accepted', 'Запрос принят'), ('rejected', 'Запрос отклонен'), ('blocked', 'Пользователь заблокирован')], default='sent', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_creator_set', to='mini_social.customuser')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to='mini_social.customuser')),
            ],
            options={
                'unique_together': {('creator', 'friend')},
            },
        ),
    ]
