# Generated by Django 4.2.6 on 2023-11-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0002_friendship_creator_block_friendship_receiver_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='creator_block',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='receiver_block',
        ),
    ]
