# Generated by Django 4.2.6 on 2023-11-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0010_message_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_deleted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='last_edited_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
