# Generated by Django 4.2.6 on 2023-11-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0011_message_last_deleted_time_message_last_edited_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='last_deleted_time',
        ),
        migrations.RemoveField(
            model_name='message',
            name='last_edited_time',
        ),
    ]
