# Generated by Django 4.2.6 on 2023-11-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0012_remove_message_last_deleted_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
