# Generated by Django 4.2.6 on 2023-11-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0013_friendship_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
