# Generated by Django 4.2.6 on 2023-11-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0014_remove_friendship_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enter_to_account',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
