# Generated by Django 4.2.6 on 2023-11-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0015_customuser_enter_to_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='enter_to_account',
            new_name='ent_to_account',
        ),
    ]
