# Generated by Django 4.2.6 on 2023-11-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0016_rename_enter_to_account_customuser_ent_to_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ent_to_account',
        ),
    ]
