# Generated by Django 4.2.6 on 2023-11-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0017_remove_customuser_ent_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time_of_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
