# Generated by Django 4.2.6 on 2023-11-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0019_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='created_at',
        ),
    ]
