# Generated by Django 4.2.6 on 2023-11-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0020_rename_time_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_social.customuser')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
