# Generated by Django 4.2.6 on 2023-12-04 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0022_comment_is_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='mini_social.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_social.customuser')),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
